import { Task, Story, PrepCard, Objection, Goal, TaskPhase, Target, Reading } from './types';

export const SEED_READING: Reading[] = [
  { id:'r1', title:'Fanatical Prospecting', author:'Jeb Blount', category:'Sales & Prospecting', type:'Book', status:'Reading', url:'https://www.google.com/search?q=Fanatical+Prospecting+Jeb+Blount', notes:'The cold-calling bible. Pull 2-3 lines for "why sales" and objection-handling answers.' },
  { id:'r2', title:'The Transparency Sale', author:'Todd Caponi', category:'Sales & Prospecting', type:'Book', status:'To read', url:'https://www.google.com/search?q=The+Transparency+Sale+Todd+Caponi', notes:'Backs up your "transparency beats pressure" roofing story with a framework.' },
  { id:'r3', title:'30 Minutes to President’s Club', author:'Armstrong & Cohen', category:'Sales & Prospecting', type:'Podcast', status:'Reading', url:'https://www.30mpc.com', notes:'Tactical SDR/AE tips in short episodes — good commute listening before interviews.' },
  { id:'r4', title:'How DNS works (comic)', author:'howdns.works', category:'Cloud & Infrastructure', type:'Article', status:'To read', url:'https://howdns.works', notes:'Cloudflare prep — be able to explain DNS, CDN and DDoS simply.' },
  { id:'r5', title:'What is observability?', author:'Datadog', category:'Data & AI', type:'Article', status:'To read', url:'https://www.datadoghq.com/knowledge-center/observability/', notes:'Datadog prep — know monitoring vs observability and who the DevOps/SRE buyer is.' },
  { id:'r6', title:'So Good They Can’t Ignore You', author:'Cal Newport', category:'Career & Switching', type:'Book', status:'Done', url:'https://www.google.com/search?q=So+Good+They+Cant+Ignore+You', notes:'Career-capital framing for the architecture → sales pivot story.' },
];

export const SEED_TARGETS: Target[] = [
  { company:'Cloudflare', tier:'stretch', tierLabel:'Stretch · most accessible', hiring:'Active — growing BDR team in Sydney for ANZ', hiringTone:'active', sells:'Network / security / CDN ("a better internet"). Buyers: IT, security & network teams (CISOs, infra leads).', prep:'Internet infrastructure basics, DDoS & security trends, why performance + security matter to enterprises.' },
  { company:'Datadog', tier:'stretch', tierLabel:'Stretch · accessible', hiring:'Active — SDR role open in Sydney, Commercial Sales', hiringTone:'active', sells:'Cloud observability / monitoring. Buyers: DevOps, SRE, engineering leaders.', prep:'Cloud monitoring concepts, what "observability" means, DevOps workflows.' },
  { company:'Snowflake', tier:'stretch', tierLabel:'Stretch', hiring:'SDR posted for AU market — entry-level w/ growth path (some ask 3+ yrs)', hiringTone:'watch', sells:'"AI Data Cloud" — cloud data warehouse. Buyers: data / analytics leaders, CDOs.', prep:'Cloud data warehouse concept, Cortex AI, MEDDIC basics.' },
  { company:'Databricks', tier:'stretch', tierLabel:'Stretch', hiring:'Mostly technical / AE roles visible — watch for BDR openings', hiringTone:'watch', sells:'Unified data + AI "lakehouse" platform. Buyers: data engineering & data science leaders.', prep:'Lakehouse vs. data warehouse, why unifying data + AI matters.' },
  { company:'Salesforce', tier:'stretch', tierLabel:'Stretch', hiring:'Futureforce graduate program (SDR/BDR rotations) — check ANZ openings', hiringTone:'watch', sells:'CRM + Agentforce (AI agents). Buyers: sales, service, marketing leaders.', prep:'CRM fundamentals, Agentforce / AI-agent positioning, MEDDIC (Salesforce-originated).' },
  { company:'Google Cloud', tier:'stretch', tierLabel:'Stretch', hiring:'SDR roles appear periodically across APAC / Sydney', hiringTone:'watch', sells:'GCP infrastructure + Gemini / Vertex AI. Buyers: enterprise IT & dev leaders.', prep:'Core GCP services, Gemini / AI positioning vs AWS & Azure.' },
  { company:'Microsoft', tier:'stretch', tierLabel:'Stretch', hiring:'Aspire early-career sales pathway (global) — confirm AU eligibility & intakes', hiringTone:'watch', sells:'Azure, M365, Dynamics, Copilot. Buyers: virtually every department.', prep:'Azure / M365 / Copilot basics, Microsoft’s growth-mindset culture language.' },
  { company:'AWS', tier:'stretch', tierLabel:'Stretch', hiring:'Sales titled "ISR" / Account Manager rather than classic SDR — check Sales/GS pages', hiringTone:'watch', sells:'Broad cloud infrastructure. Buyers: virtually all enterprise IT.', prep:'Core AWS services (EC2, S3, RDS, Lambda), Amazon Leadership Principles.' },
  { company:'Atlassian', tier:'step', tierLabel:'Stepping-stone · Sydney HQ', hiring:'Check careers page regularly', hiringTone:'watch', sells:'Jira, Confluence, dev / IT collaboration tools. Buyers: dev & IT teams.', prep:'Product-led growth motion, dev team workflows.' },
  { company:'Canva', tier:'step', tierLabel:'Stepping-stone · Sydney HQ', hiring:'Check careers page regularly', hiringTone:'watch', sells:'Design platform. Buyers: marketing & design teams.', prep:'Product-led growth, design-to-business value story (strong fit for your background).' },
  { company:'HubSpot', tier:'step', tierLabel:'Stepping-stone · Sydney office', hiring:'Check careers page regularly', hiringTone:'watch', sells:'CRM / marketing platform. Buyers: SMB & mid-market marketing / sales leaders.', prep:'Inbound methodology (their own framework — also useful for your certs).' },
  { company:'Xero', tier:'step', tierLabel:'Stepping-stone · NZ-origin, AU presence', hiring:'Check careers page regularly', hiringTone:'watch', sells:'Accounting SaaS. Buyers: SMBs & accountants.', prep:'SMB SaaS sales motion, volume-based selling.' },
  { company:'ServiceNow / Workday', tier:'step', tierLabel:'Stepping-stone', hiring:'Check careers pages regularly', hiringTone:'watch', sells:'ITSM / HR & Finance SaaS. Buyers: enterprise IT ops / HR & Finance leaders.', prep:'Enterprise workflow software positioning.' },
  { company:'MongoDB / Okta / Zscaler', tier:'step', tierLabel:'Stepping-stone', hiring:'Check careers pages regularly', hiringTone:'watch', sells:'Database / identity / zero-trust security. Buyers: dev & security teams.', prep:'Modern database concepts; identity & zero-trust security basics.' },
  { company:'monday.com / Twilio', tier:'step', tierLabel:'Stepping-stone', hiring:'Check careers pages regularly', hiringTone:'watch', sells:'Work management / communication APIs. Buyers: ops teams & developers.', prep:'Work management platforms; API-driven communication products.' },
  { company:'Kong · Glean · V2.ai · DNX Solutions', tier:'step', tierLabel:'Stepping-stone', hiring:'Check careers pages regularly', hiringTone:'watch', sells:'Smaller / emerging ANZ tech & cloud players worth monitoring.', prep:'Watch list — apply opportunistically when openings appear.' },
];

export const DEFAULT_GOAL_ID = 'goal_sdr';
export const SEED_PHASE_IDS: Record<TaskPhase, string> = { 'Phase 1': 'p1', 'Phase 2': 'p2', 'Phase 3': 'p3' };

export const DEFAULT_GOAL: Goal = {
  id: DEFAULT_GOAL_ID,
  name: 'Break into tech sales',
  description: 'Land an SDR/BDR role in Sydney',
  color: '#F5552E',
  targetDate: '2026-09-01',
  phases: [
    { id: 'p1', name: 'Foundations', description: 'Numbers, LinkedIn, story, resume & certs', startDate: '2026-06-15', endDate: '2026-07-10' },
    { id: 'p2', name: 'Networking & Applications', description: 'Warm outreach, target research, first applications', startDate: '2026-07-13', endDate: '2026-08-07' },
    { id: 'p3', name: 'Volume & Move', description: 'Volume applications, interview blitz, relocate', startDate: '2026-08-10', endDate: '2026-09-04' },
  ],
};

export const SEED_TASKS: Task[] = [
  { id:'p1w1_1', phase:'Phase 1', week:'Week 1 — Numbers, LinkedIn & Story', priority:'High', isNew:true,
    task:'Confirm financial buffer — exact Sydney living costs and where the money comes from',
    notes:'Sydney min buffer ~$12k AUD (rent ~$2.5k/mo + living ~$1.5k/mo × 3). Don\'t leave this to week 8.' },
  { id:'p1w1_2', phase:'Phase 1', week:'Week 1 — Numbers, LinkedIn & Story', priority:'High',
    task:'Rewrite LinkedIn headline',
    notes:'"Architecture → Tech Sales | Building outbound fundamentals at SRL | Relocating to Sydney Sep 2026"' },
  { id:'p1w1_3', phase:'Phase 1', week:'Week 1 — Numbers, LinkedIn & Story', priority:'High',
    task:'Rewrite LinkedIn About section',
    notes:'Bridge architecture → sales: client consultation, deliberate pivot, SRL work, NZ citizen with AU work rights.' },
  { id:'p1w1_4', phase:'Phase 1', week:'Week 1 — Numbers, LinkedIn & Story', priority:'High',
    task:'Update SRL experience on LinkedIn with metrics',
    notes:'Add AI price estimator + visual comparison tools + calls made + appointments booked.' },
  { id:'p1w1_5', phase:'Phase 1', week:'Week 1 — Numbers, LinkedIn & Story', priority:'Medium',
    task:'Update LinkedIn profile photo and banner',
    notes:'Professional photo, clean background. Banner: simple or Sydney skyline.' },
  { id:'p1w1_6', phase:'Phase 1', week:'Week 1 — Numbers, LinkedIn & Story', priority:'High',
    task:'Set up job alerts on LinkedIn for SDR/BDR Sydney',
    notes:'"Sales Development Representative Sydney" + "Business Development Representative Sydney"' },
  { id:'p1w1_7', phase:'Phase 1', week:'Week 1 — Numbers, LinkedIn & Story', priority:'High',
    task:'Tell your story out loud — 3× per day, every day this week',
    notes:'5 beats: architecture ceiling → AI clarity → SRL fundamentals → what I built → why tech. Record once, watch back.' },
  { id:'p1w1_8', phase:'Phase 1', week:'Week 1 — Numbers, LinkedIn & Story', priority:'High',
    task:'Log all roofing calls daily — build the habit now',
    notes:'Date, name, outcome, next step. This becomes your interview data story.' },
  { id:'p1w2_1', phase:'Phase 1', week:'Week 2 — Resume & Cert', priority:'High',
    task:'Write a one-page SDR resume', notes:'Header, summary, SRL role with metrics, architecture proof points, certs.' },
  { id:'p1w2_2', phase:'Phase 1', week:'Week 2 — Resume & Cert', priority:'High',
    task:'Enrol in HubSpot Sales Software certification', notes:'Free, recognised, done in a weekend.' },
  { id:'p1w2_3', phase:'Phase 1', week:'Week 2 — Resume & Cert', priority:'Medium',
    task:'Enrol in Salesforce Trailhead ADM101 badges', notes:'Basics. Employers expect it.' },
  { id:'p1w3_1', phase:'Phase 1', week:'Week 3 — Story Bank', priority:'High',
    task:'Write 8–10 STAR stories covering the key SDR interview questions',
    notes:'Structured, Situation-Task-Action-Result. Tag each to the questions it answers.' },
  { id:'p1w3_2', phase:'Phase 1', week:'Week 3 — Story Bank', priority:'Medium',
    task:'Record yourself answering 5 hardest questions on video', notes:'Watch back once. Fix posture and pace.' },
  { id:'p2w1_1', phase:'Phase 2', week:'Week 4 — Warm Outreach', priority:'High',
    task:'Message 20 warm contacts about your move', notes:'LinkedIn DMs. Keep it real, not transactional.' },
  { id:'p2w1_2', phase:'Phase 2', week:'Week 4 — Warm Outreach', priority:'High',
    task:'Book 5 coffee chats / informational interviews', notes:'SDRs at target companies first.' },
  { id:'p2w2_1', phase:'Phase 2', week:'Week 5 — Target Research', priority:'High',
    task:'Research top 10 target companies deeply', notes:'Product, ICP, competitors, recent news, who buys.' },
  { id:'p2w2_2', phase:'Phase 2', week:'Week 5 — Target Research', priority:'Medium',
    task:'Follow key people at target companies on LinkedIn', notes:'Comment thoughtfully — don\'t just like.' },
  { id:'p2w3_1', phase:'Phase 2', week:'Week 6 — First Outreach Wave', priority:'High',
    task:'Send 30 personalised cold LinkedIn messages to SDR/Sales leaders', notes:'One thing specific per message. No spray and pray.' },
  { id:'p3w1_1', phase:'Phase 3', week:'Week 7 — Volume Applications', priority:'High',
    task:'Apply to 5 new roles per day', notes:'Quality > quantity, but you need the reps. Track every one.' },
  { id:'p3w1_2', phase:'Phase 3', week:'Week 7 — Volume Applications', priority:'High',
    task:'Customise each cover letter with one company-specific paragraph', notes:'Research → company problem → how you solve it.' },
  { id:'p3w2_1', phase:'Phase 3', week:'Week 8 — Interview Blitz', priority:'High',
    task:'Run 10 mock interviews', notes:'Two cold: one tech, one non-tech person who doesn\'t know the script.' },
  { id:'p3w2_2', phase:'Phase 3', week:'Week 8 — Interview Blitz', priority:'Medium',
    task:'Research each interviewer 15 mins before the call', notes:'LinkedIn + company news. One relevant observation ready.' },
];

export const SEED_STORIES: Story[] = [
  { id:'s1', date:'17 Jun', title:'Handling a hostile prospect and still booking',
    situation:'A homeowner opened with "you lot are all rip-offs" before I\'d said anything beyond my name.',
    task:'De-escalate, reframe value, and earn a free assessment.',
    action:'Acknowledged his frustration first, asked what had happened, let him vent, then slowly reframed our process as different — transparency, written quote, no pressure.',
    result:'Booked the assessment. He became one of our most collaborative customers. Taught me composure and curiosity beat a polished pitch.',
    question:'Tell me about a difficult prospect · How do you handle rejection?' },
  { id:'s2', date:'10 Jun', title:'Building an AI price estimator nobody asked for',
    situation:'At SRL, quoting was slow and inconsistent, which cost us speed-to-lead on inbound enquiries.',
    task:'Find a way to respond to leads faster without waiting on a manual quote.',
    action:'Taught myself the tooling and built an AI-assisted price estimator and a visual comparison tool, then rolled it into my own call workflow.',
    result:'Faster, more confident first calls and a repeatable process. Proof I spot problems and ship solutions without being told to.',
    question:'Tell me about a time you took initiative · A time you taught yourself something' },
  { id:'s3', date:'02 Jun', title:'Pivoting from architecture into sales on purpose',
    situation:'Years into architecture I hit a ceiling where the work no longer matched where I wanted to grow.',
    task:'Make a deliberate, credible move into tech sales rather than a panicked career flip.',
    action:'Took an SDR-style roofing role to learn outbound fundamentals, built this tracking system, and started certifications and outreach before applying.',
    result:'A real story backed by data — not "I think I\'d be good at sales" but "here\'s the pipeline I\'ve already run".',
    question:'Why are you changing careers? · Why sales?' },
];

export const SEED_PREP: PrepCard[] = [
  { id:'q1', tag:'Opener', q:'Tell me about yourself.',
    a:'Architecture taught me to consult clients and translate technical detail for non-technical people. I deliberately moved into outbound sales at SRL to build the fundamentals — cold calling, objection handling, CRM. Now I\'m relocating to Sydney to do that full-time in tech.' },
  { id:'q2', tag:'Motivation', q:'Why sales?',
    a:'I like the parts of architecture that were really sales — understanding what someone actually needs and guiding a decision. Sales is that, but faster, more measurable, and more meritocratic. I want a scoreboard.' },
  { id:'q3', tag:'Company', q:'Why this company?',
    a:'Lead with the product angle, the buyer persona, and one recent news item. E.g. Cloudflare: security + performance infra, sold to CISOs and infra leads — a more substantive technical conversation, which suits my background.' },
  { id:'q4', tag:'Objection', q:'Why hire you over someone with SDR experience?',
    a:'Years of client consultation, translating complexity for non-technical buyers, and staying calm under pressure. I\'ve already proven I can cold call and handle objections — I just did it in roofing instead of SaaS.' },
  { id:'q5', tag:'Resilience', q:'How do you handle rejection?',
    a:'Roofing cold calls are mostly no\'s. I treat each call as a rep, track outcomes, and look for one thing to improve. My confidence score went from a 4 in week one to a 7 — because I measured it.' },
  { id:'q6', tag:'Skill', q:'Walk me through a cold call.',
    a:'Opener (permission) → reason for the call → a qualifying question → ask for the meeting → handle the objection → re-ask. Smile before you dial; the goal is the next step, not the close.' },
  { id:'q7', tag:'Growth', q:'Where do you see yourself in 3–5 years?',
    a:'SDR → AE in 12–18 months as a top performer, mid-market AE by year three. Tech sales rewards results, and I intend to be measurable from day one.' },
  { id:'q8', tag:'Self-aware', q:'What\'s your biggest weakness?',
    a:'I can over-prepare. In roofing I learned that done beats perfect — a good call today beats a perfect script next week. I now set a time box and make the dial.' },
];

export const SEED_OBJECTIONS: Objection[] = [
  { id:'o1', tag:'Price', objection:'It\'s too expensive / too much money.',
    response:'I understand. Just curious — how does the current cost compare to the revenue you\'re losing right now?' },
  { id:'o2', tag:'Competitor', objection:'We already use a competitor.',
    response:'Totally fair. What made you choose them originally? I\'d love to understand what\'s working well.' },
  { id:'o3', tag:'Timing', objection:'Now\'s not a good time.',
    response:'I appreciate the honesty. When would be a better window — is it more of a budget cycle thing or a priority thing?' },
  { id:'o4', tag:'Brush off', objection:'Just send me some information.',
    response:'Happy to. So I send the most relevant stuff — what\'s the one thing you\'d most want it to answer?' },
  { id:'o5', tag:'No need', objection:'We don\'t have that problem.',
    response:'That\'s great to hear. Out of curiosity, how are you currently handling [specific thing]?' },
  { id:'o6', tag:'Decision', objection:'I\'d have to talk to my manager.',
    response:'Of course. If you were presenting this internally, what would be the first question they\'d ask?' },
  { id:'o7', tag:'Sceptical', objection:'We\'ve tried things like this before — it didn\'t work.',
    response:'That\'s a fair concern. What happened? I want to understand what went wrong so I don\'t waste your time.' },
  { id:'o8', tag:'No budget', objection:'We don\'t have budget right now.',
    response:'Understood. Is that a firm freeze, or more of a timing thing? Sometimes we can structure things around a cycle.' },
];
